---
output:
  pdf_document:
    latex_engine: xelatex
---

\newpage
# BÀI TẬP 5
**Xem xét phân phối Weibull với hàm mật độ xác suất như sau:**
$$\boldsymbol {f(y;\alpha,\gamma) = \frac{\alpha}{\gamma}.(\frac{y}{\gamma})^{\alpha-1}.exp[-(\frac{y}{\gamma})^\alpha]}$$
**Với $y>0, \alpha >0, \text{ và } \gamma >0$**
\vspace{1cm}

## Câu 1:    
**Chứng minh rằng, về mặt tổng quát phân phối Weibull không thuộc vào họ phân phối mũ phân tán.**

\vspace{0.5cm}
Ta có:   

$\hspace{2cm}f(y;\alpha, \gamma)=\frac{\alpha}{\gamma}.(\frac{y}{\gamma})^{\alpha-1}.exp[-(\frac{y}{\gamma})^\alpha]$   

Lấy logarit của $f(y;\alpha, \gamma)$, ta được:   

$\hspace{2cm}logf(y;\alpha, \gamma)=log(\frac{\alpha}{\gamma}) + (\alpha -1).log(\frac{y}{\gamma}) - (\frac{y}{\gamma})^\alpha$  

$\hspace{2cm}logf(y;\alpha, \gamma)=log(\alpha) - log(\gamma) + (\alpha -1).[log(y)-log(\gamma)] - (\frac{y}{\gamma})^\alpha$   

$\hspace{2cm}logf(y;\alpha, \gamma)=log(\alpha) - log(\gamma) + (\alpha -1).log(y)- (\alpha - 1).log(\gamma) - (\frac{y}{\gamma})^\alpha$    

$\hspace{2cm}logf(y;\alpha, \gamma)=log(\alpha) - log(\gamma) + (\alpha -1).log(y) - \alpha.log(\gamma) + log(\gamma) - (\frac{y}{\gamma})^\alpha$    

$\hspace{2cm}logf(y;\alpha, \gamma)=log(\alpha)  + (\alpha -1).log(y) - \alpha.log(\gamma) - (\frac{y}{\gamma})^\alpha$    

$\hspace{2cm}logf(y;\alpha, \gamma)=[{- (y)}^\alpha.\gamma^{-\alpha}]   + log(\alpha) - \alpha.log(\gamma)+ (\alpha -1).log(y)$  **\hfill (1)**

Suy ra,    

$\hspace{2cm}f(y;\alpha, \gamma)=exp[{- (y)}^\alpha.\gamma^{-\alpha}] .\frac{\alpha}{\gamma^\alpha} .y^{\alpha -1}$   

Vậy trong trường hợp tổng quát, phân phối Weibull không thuộc vào họ phân phối mũ phân tán

\newpage
## Câu 2:   
**Chứng minh rằng nếu $\alpha=1$, phân phối Weibull thuộc vào họ phân phối mũ phân tán. Khi này, xác định tham số tự nhiên $\theta$, tham số phân tán $\phi$, các hàm $b(\theta)$, $a(\phi)$ và $c(\phi; y)$**

\vspace{0.5cm}
Khi $\alpha = 1$, **(1)** thành:

$\hspace{2cm}logf(y;\gamma)=[- (y).\gamma^{-1}]  - log(\gamma)$   

$\hspace{2cm}f(y;\gamma)=\gamma^{-1}.exp(\frac{- y}{\gamma})$   

Vậy khi $\alpha = 1$ thì phân phối Weibull thuộc vào họ phân phối mũ phân tán với:   

- Tham số tự nhiên $\theta$ là $\gamma$    
- Tham số phân tán $\phi$ là $\alpha$    
- Hàm $a(\phi)$ là 1   
- Hàm $b(\theta)$ là $\gamma^{-1}$   
- Hàm $c(\phi,y)$ là $exp(\frac{- y}{\gamma})$

## Câu 3:  
**Xác định hàm liên kết chính tắc.**

\vspace{0.5cm}   
Hàm liên kết chính tắc là liên hệ giữa kỳ vọng $\mu = E[Y]$ và tham số tự nhiên $\theta$. Với phân phối mũ $(\alpha = 1)$. Ta có:   

$$\mu=-\frac{1}{\theta^\alpha} = -\frac{1}{\theta}$$
Do đó, hàm liên kết chính tắc là:
$$\theta=-\frac{1}{\mu}$$




















