\newpage
## Xác định hàm liên kết chính tắc, hàm liên kết không chính tắc

\vspace{1cm}
Ta có: 
                                                            
$\hspace{2cm} f_Y(y_i|\theta_i,\phi) = exp\{y_i\theta_i - m_ilog(1+e^{\theta_i}) + log(C_{y_i}^{m_i}) \}$    

$\hspace{1cm}\text{Với}$:  

$\hspace{2cm}\theta_i = log(\frac{p_i}{1-p_i})$

$\hspace{2cm} b(\theta_i) = m_ilog(1+e^{\theta_i})$    

$\hspace{2cm} a(\phi) = 1$    

$\hspace{2cm} c(y_i,\phi) = log(C_{y_i}^{m_i})$    

\vspace{0.5 cm}
Tính kỳ vọng của Y:

$\hspace{2cm} E[y_i] = \frac{\partial}{\partial\theta_i}b(\theta_i)$    

$\hspace{3cm} \Leftrightarrow  E[y_i] = \frac{\partial}{\partial\theta_i}m_ilog(1+e^{\theta_i})$    

$\hspace{3cm} \Leftrightarrow  E[y_i] = m_i\frac{e^{\theta_i}}{1+e^{\theta_i}}$    

$\hspace{3cm} \Leftrightarrow  E[y_i] = m_ip_i$ (Do **1.1**) **\hfill (3)**

\vspace{0.5 cm}
Ta có:

$\hspace{2cm} \mu_i = E[y_i]$

$\hspace{3cm} \Leftrightarrow \mu_i = m_ip_i$ (Do **3**)

$\hspace{3cm} \Leftrightarrow p_i= \frac{\mu_i}{m_i}$ 

\vspace{0.5 cm}
Mà:

$\hspace{2cm} \theta_i = log(\frac{p_i}{1-p_i})$ 

$\hspace{3cm} \Leftrightarrow \theta_i = log(\frac{\frac{\mu_i}{m_i}}{1-\frac{\mu_i}{m_i}})$ 

Vậy hàm liên kết chính tắc là $\theta_i = log(\frac{\frac{\mu_i}{m_i}}{1-\frac{\mu_i}{m_i}})$ 

Vậy hàm liên kết là $\eta_i = log(\frac{\mu_i}{1-\mu_i}) = log(\frac{m_i p_i}{1-m_i p_i})$ 

