## Kiểm tra $Y_i$~$B(m_i,p_i)$ có thuộc họ phân phối mũ phân tán   

\vspace{1cm}

Ta có hàm phân phối nhị thức:  
                                                            
$\hspace{2cm} f_Y(y_i) = C_{m_i}^{y_i}p_i^{y_i}(1-p_i)^{m_i-y_i}\\\\$    

Lấy log 2 vế, ta được:

$\hspace{2cm} log[f_Y(y_i)] = log(C_{m_i}^{y_i}) + y_ilog(p_i) + (m_i-y_i)log(1-p_i)\\\\$    

Đưa về dạmg lũy thừa, ta được:  

$\hspace{2cm} f_Y(y_i) = exp\{log(C_{m_i}^{y_i}) + y_ilog(p_i) + (m_i-y_i)log(1-p_i)\}\\$    

$\hspace{2cm} f_Y(y_i) = exp\{log(C_{m_i}^{y_i}) + y_ilog(p_i) + m_ilog(1-p_i) - y_ilog(1-p_i)\}\\$    

$\hspace{2cm} f_Y(y_i) = exp\{log(C_{m_i}^{y_i}) + y_i[log(p_i) - log(1-p_i)]+ m_ilog(1-p_i) \}\\$    

$\hspace{2cm} f_Y(y_i) = exp\{y_ilog(\frac{p_i}{1-p_i})+ m_ilog(1-p_i) + log(C_{m_i}^{y_i}) \}$   **\hfill (\*)** 
    
\vspace{1cm}
Đặt: 

$\hspace{2cm}\theta_i = log(\frac{p_i}{1-p_i})$ **\hfill (1)** 

$\hspace{3cm}\Leftrightarrow e^{\theta_i} = \frac{p_i}{1-p_i} \\$

$\hspace{3cm}\Leftrightarrow p_i = (1-p_i)e^{\theta_i} \\$

$\hspace{3cm}\Leftrightarrow p_i(1+e^{\theta_i}) = e^{\theta_i} \\$

$\hspace{3cm}\Leftrightarrow p_i = \frac{e^{\theta_i}}{1+e^{\theta_i}}$ **\hfill (1.1)**
  
\vspace{1cm}
Với:   

$\hspace{2cm} p_i = \frac{e^{\theta_i}}{1+e^{\theta_i}}\\$  

$\hspace{3cm} \Rightarrow {1-p_i} = 1-\frac{e^{\theta_i}}{1+e^{\theta_i}}\\$  

$\hspace{3cm} \Leftrightarrow {1-p_i} = \frac{1+e^{\theta_i}-e^{\theta_i}}{1+e^{\theta_i}}\\$   

$\hspace{3cm} \Leftrightarrow {1-p_i} = (1+e^{\theta_i})^{-1}\\\\$   

  
$\hspace{2cm} {1-p_i} = (1+e^{\theta_i})^{-1}$   **\hfill (2.1)**

$\hspace{3cm}\Rightarrow m_ilog(1-p_i) = m_ilog(1+e^{\theta_i})^{-1}\\$   

$\hspace{3cm}\Leftrightarrow m_ilog(1-p_i) = -m_ilog(1+e^{\theta_i})$ **\hfill (2)**   
      
\vspace{1cm}
Thế **(1), (2)** vào **(\*)**. Ta được:

$\hspace{2cm} f_Y(y_i|\theta_i) = exp\{y_i\theta_i - m_ilog(1+e^{\theta_i}) + log(C_{y_i}^{m_i}) \}$    

$\hspace{3cm} \Leftrightarrow f_Y(y_i|\theta_i,\phi) = exp\{\frac{y_i\theta_i - b(\theta_i)}{a(\phi)} + c(y_i,\phi) \}$    

$\hspace{1cm}\text{Với}$:  

$\hspace{2cm} \theta_i = log(\frac{p_i}{1-p_i})$    

$\hspace{2cm} b(\theta_i) = m_ilog(1+e^{\theta_i})$    

$\hspace{2cm} a(\phi) = 1$    

$\hspace{2cm} c(y_i,\phi) = log(C_{y_i}^{m_i})$    

Vậy $Y_i$~$B(m_i,p_i)$ thuộc họ phân phối mũ phân tán   

